spring.datasource.url=jdbc:postgresql://localhost:5432/shop
spring.datasource.username=hossein
spring.datasource.password=13851385
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.open-in-view=false

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/changelog-master.xml

server.error.whitelabel.enabled=false

logging.level.web=trace
logging.level.sql=trace

server.servlet.context-path=/api/v1/payment
server.port=8082


user.service.base-url=http://localhost:8080/api/v1/user/users
shop.cardId=100000037